### PR TITLE
fix package version ranges

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by WilliamBZA** [comment]
Seems like this has broken some of the versions that the tests expect

**Comment by SimonCropp** [comment]
@WilliamBZA sorry. fixed

**Comment by timbussmann** [comment]
if you would also adjust gitversion to create a beta package on the release branch, we could push this package to beta after this PR.

**Comment by WilliamBZA** [comment]
@timbussmann how would I do that?

**Comment by timbussmann** [comment]
@WilliamBZA change the gitversion file to look like this: https://github.com/Particular/NServiceBus/blob/develop/GitVersion.yml

**Pull request merged**
