### PR TITLE
Release 5.1.0

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by andreasohlund** [comment]
6 failing acceptance tests, wonder if we have to upgrade NUnit?

**Comment by danielmarbach** [comment]
@WilliamBZA @andreasohlund upgraded NUnit to 3.2.1 as a starter (core uses that version), let's see if it works. Had to hack two acceptance tests and the setup fixture

**Comment by andreasohlund** [comment]
6 failing tests, pretty sure all are those callstack asserts so we can just remove them?

**Comment by danielmarbach** [comment]
Removed the asserts

**Comment by andreasohlund** [comment]
Test are green, LGTM

**Pull request merged**
