### PR TITLE
Update to Autofac 4

### PR DESCRIPTION
**Pull request by andreasohlund**
Replaces #18 and will mean that v6 will be targeting AF 4

### CODE REVIEW

**Comment by valeriob** [comment]
Hi there, does this mean that if i want to upgrade autofac to version 4 i'm forced to use NSB 6 ?

**Comment by danielmarbach** [comment]
@andreasohlund let us have a look at the breaking changes of Autofac 4.0. We might be able to release a 5.x version of the adapter.

**Comment by danielmarbach** [comment]
@valeriob raised https://github.com/Particular/NServiceBus.Autofac/issues/22

**Comment by danielmarbach** [comment]
@valeriob see https://github.com/Particular/NServiceBus.Autofac/pull/23

**Comment by andreasohlund** [comment]
What version arr you currently on? We can definitely backport a v5 compatible version.

**Comment by valeriob** [comment]
Very good news, yes we are on nsb 5.

**Comment by danielmarbach** [comment]
@valeriob The release is on myget. I will smoke test it on the docs site and then release it. Should be there at the end of the day or tomorrow.

**Comment by danielmarbach** [comment]
@valeriob The release is available [on nuget](https://www.nuget.org/packages/NServiceBus.Autofac/5.1.0).

**Pull request merged**
